#!/usr/bin/env bash
# gz_hotspots.sh — Find Gazebo functions in the hot path
#
# Usage: ./gz_hotspots.sh <file.folded> [top_n]
#
# Analyzes a collapsed stack file and identifies Gazebo-owned functions
# that consume the most CPU. These are optimization candidates because
# we can change how they work (skip calls, reduce frequency, use better
# algorithms) even though the actual CPU may be spent inside libraries
# they call (DART, ODE, STL, etc.).
#
# Prerequisites:
#   - A .folded file generated by stackcollapse-perf.pl

set +o pipefail

FOLDED="${1:?Usage: $0 <file.folded> [top_n]}"
TOP_N="${2:-15}"

if [[ ! -f "$FOLDED" ]]; then
    echo "ERROR: File not found: $FOLDED" >&2
    exit 1
fi

TOTAL=$(awk '{s+=$NF} END {print s}' "$FOLDED")
LABEL=$(basename "$FOLDED" .folded)

# Gazebo namespace pattern — functions we can modify
GZ_PATTERN='gz::sim::|gz::physics::dartsim::|gz::rendering::|gz::common::|gz::math::|gz::transport::|gz::plugin::|gz::msgs::|gz::sensors::|SimulationRunner::|SimulationFeatures::|gz::sim::v11::systems::|gz::sim::v11::detail::|gz::sim::v11::Entity|stbi__|gz::common::Image|SdfModelSerializer|ServerPrivate::DownloadAssets|ServerPrivate::LoadSdfRoot|pybind11::initialize'

# Truncate long C++ template names for display
truncate_name() {
    awk -F'\t' '{
        name = $2
        # Truncate after first < if name is too long
        if (length(name) > 70) {
            idx = index(name, "<")
            if (idx > 0) name = substr(name, 1, idx-1) "<...>"
        }
        printf "%s\t%s\n", $1, name
    }'
}

echo "============================================"
echo "  Gazebo Hotspot Analysis: $LABEL"
echo "============================================"
echo "  Total samples: $TOTAL"
echo ""

# ---------------------------------------------------------------
# 1. Optimization targets: Gazebo functions with highest inclusive time
# ---------------------------------------------------------------
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  1. Optimization targets (inclusive time)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Gazebo functions ranked by total CPU spent under them"
echo "  (including all children). If you optimize or remove one"
echo "  of these functions, you'd save up to this % of CPU."
echo "  These are the primary optimization candidates."
echo ""

awk '{
    n = split($1, a, ";")
    samples = $NF
    seen = ""
    for (i = 1; i <= n; i++) {
        func = a[i]
        if (index(seen, "|" func "|") > 0) continue
        seen = seen "|" func "|"
        printf "%s\t%d\n", func, samples
    }
}' "$FOLDED" \
    | awk -F'\t' '{s[$1]+=$2} END {for(k in s) printf "%d\t%s\n",s[k],k}' \
    | grep -E "$GZ_PATTERN" \
    | grep -v -E '^[0-9]+\tgz-sim-main$' \
    | sort -rn \
    | head -"$TOP_N" \
    | truncate_name \
    | awk -F'\t' -v total="$TOTAL" '{
        pct = $1 * 100.0 / total;
        printf "%6.1f%%  %s\n", pct, $2
    }'

echo ""

# ---------------------------------------------------------------
# 2. What these functions call: attribution of external costs
# ---------------------------------------------------------------
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  2. What Gazebo functions call (attribution)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  For each sample, finds the nearest Gazebo function in the"
echo "  stack and shows what external function it called. Format:"
echo "  GazeboFunc -> ExternalFunc. Shows where optimizing the"
echo "  Gazebo caller would reduce external library cost."
echo ""

awk '{
    n = split($1, a, ";")
    samples = $NF
    leaf = a[n]

    gz_caller = ""
    for (i = n; i >= 1; i--) {
        if (match(a[i], /gz::sim::|gz::physics::dartsim::|gz::rendering::|gz::common::|gz::transport::|gz::sensors::|SimulationRunner::|SimulationFeatures::|ServerPrivate::/)) {
            gz_caller = a[i]
            break
        }
    }

    if (gz_caller != "" && gz_caller != leaf) {
        printf "%s -> %s\t%d\n", gz_caller, leaf, samples
    }
}' "$FOLDED" \
    | awk -F'\t' '{s[$1]+=$2} END {for(k in s) printf "%d\t%s\n",s[k],k}' \
    | sort -rn \
    | head -"$TOP_N" \
    | truncate_name \
    | awk -F'\t' -v total="$TOTAL" '{
        pct = $1 * 100.0 / total;
        printf "%6.1f%%  %s\n", pct, $2
    }'

echo ""

# ---------------------------------------------------------------
# 3. External costs for context (not directly actionable)
# ---------------------------------------------------------------
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  3. External costs (context)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Top CPU consumers in external libraries (DART, ODE, Ogre,"
echo "  glibc, etc.). Not directly actionable, but shows where"
echo "  the CPU actually executes. See section 2 for which Gazebo"
echo "  function is responsible for each."
echo ""

EXT_PATTERN='dart::|dxHash|dxGeom|dxSafe|dxSpace|Ogre::|libnvidia|\[libdart|\[unknown\]|pthread_|_int_free|_int_malloc|malloc_consolidate|__memset|__memmove|__memcpy|\[\[vdso\]\]|BoxedLcp|ConstraintSolver|ConstrainedGroup|BodyNode::|Frame::get|DegreeOfFreedom::|Skeleton::|CollisionGroup::|CollisionObject::|ContactConstraint|OdeCollisionDetector|BulletCollisionDetector|ForwardStep::World'

awk '{ n=split($1,a,";"); printf "%s\t%d\n", a[n], $NF }' "$FOLDED" \
    | awk -F'\t' '{s[$1]+=$2} END {for(k in s) printf "%d\t%s\n",s[k],k}' \
    | grep -E "$EXT_PATTERN" \
    | sort -rn \
    | head -"$TOP_N" \
    | truncate_name \
    | awk -F'\t' -v total="$TOTAL" '{
        pct = $1 * 100.0 / total;
        printf "%6.1f%%  %s\n", pct, $2
    }'

echo ""

# ---------------------------------------------------------------
# Summary
# ---------------------------------------------------------------
echo "============================================"
echo "  Summary"
echo "============================================"
echo "  How much CPU runs under a Gazebo function in the call stack?"
echo "  This is the portion we can influence by changing Gazebo code."
echo ""

awk -v total="$TOTAL" '
BEGIN { gz=0; other=0 }
{
    n = split($1, a, ";")
    samples = $NF
    found_gz = 0
    for (i = n; i >= 1; i--) {
        if (match(a[i], /gz::sim::|gz::physics::dartsim::|gz::rendering::|gz::common::|gz::math::|gz::transport::|gz::sensors::|SimulationRunner::|SimulationFeatures::|gz::sim::v11::systems::|gz::sim::v11::detail::|ServerPrivate::/)) {
            found_gz = 1
            break
        }
    }
    if (found_gz) gz += samples
    else other += samples
}
END {
    printf "  Under Gazebo code: %5.1f%%  (optimization opportunity)\n", gz * 100.0 / total
    printf "  Outside Gazebo:    %5.1f%%  (external threads, drivers, kernel)\n", other * 100.0 / total
}' "$FOLDED"
